force afs backup script to run as root, because we're using -localauth
git-svn-id: svn+ssh://svn.tursom.org/home/svn_garden/svn/garden@10 43d5e740-1f74-4541-a50a-54ab1b6ba2ff

diff --git a/afs/tursom_afs_user_backup b/afs/tursom_afs_user_backup
--- a/afs/tursom_afs_user_backup
+++ b/afs/tursom_afs_user_backup
@@ -1,6 +1,11 @@
 #!/bin/bash
 # $Id$
 
+if [ $EUID != "0" ]; then
+    echo "ERROR: must be run as root"
+    exit 1
+fi
+
 PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
 VOLS=`vos listvldb -localauth | grep '^u\.'`
 vos backupsys -prefix u. -localauth >/dev/null 2>&1
