add ~/.{bashrc,bash_profile,bash_logout} allow for non-root installs via setup if needed
git-svn-id: svn+ssh://svn.tursom.org/home/svn_garden/svn/garden@5 43d5e740-1f74-4541-a50a-54ab1b6ba2ff

diff --git a/gen/setup_hdr b/gen/setup_hdr
--- a/gen/setup_hdr
+++ b/gen/setup_hdr
@@ -1,9 +1,14 @@
+# -*- shell-script -*-
 # $Id$
+
 INST="/usr/bin/install"
 INST_N="${INST} -o root -g root"
 
-if [ $EUID != "0" ]; then
-  echo "ERROR: must run as root/sudo"
+if [ $EUID != "0" ] && [ x"${NOROOT}" = "x" ]; then
+  echo "ERROR: must run as root/sudo" >&2
+  exit 1
+elif [ $EUID = "0" ] && [ x"${NOROOT}" != "x" ]; then
+  echo "ERROR: no root was specified, but we are root!" >&2
   exit 1
 fi
 
